#!/usr/bin/env python3
"""
gen_forwarders.py — generate forwarders_generated.c and winmm.def

Reads the export table of the genuine winmm.dll and, for every export EXCEPT
the joystick functions we implement ourselves, emits:

  * a void* pointer  p_<Name>
  * an x86 naked thunk  thunk_<Name>:  jmp dword ptr [p_<Name>]
  * a .def line         <Name>=thunk_<Name>
  * a resolver line in  resolve_forwarders()

The joy* overrides are listed in the .def pointing at our own implementations.

Two backends: 'pefile' (cross-platform, pip install pefile) or Windows
'dumpbin /exports'. Run on the machine you build on so the table matches.

Usage:
  python gen_forwarders.py [--winmm C:\\Windows\\System32\\winmm.dll] [--out ../src]
"""
import argparse, os, re, subprocess, sys

# Functions WE implement (must NOT be forwarded). Keep in sync with joystick.cpp.
OVERRIDES = {
    "joyGetPosEx", "joyGetPos", "joyGetNumDevs",
    "joyGetDevCapsA", "joyGetDevCapsW",
    "joyGetThreshold", "joySetThreshold", "joyConfigChanged",
    "joySetCapture", "joyReleaseCapture",
}

def exports_via_pefile(path):
    import pefile
    pe = pefile.PE(path, fast_load=True)
    pe.parse_data_directories(
        directories=[pefile.DIRECTORY_ENTRY['IMAGE_DIRECTORY_ENTRY_EXPORT']])
    names = []
    for exp in pe.DIRECTORY_ENTRY_EXPORT.symbols:
        if exp.name:
            names.append(exp.name.decode())
    return names

def exports_via_dumpbin(path):
    out = subprocess.check_output(["dumpbin", "/exports", path],
                                  universal_newlines=True)
    names = []
    for line in out.splitlines():
        m = re.match(r"\s*\d+\s+[0-9A-Fa-f]+\s+[0-9A-Fa-f]+\s+(\w+)", line)
        if m:
            names.append(m.group(1))
    return names

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--winmm", default=r"C:\Windows\System32\winmm.dll")
    ap.add_argument("--out", default=os.path.join(os.path.dirname(__file__), "..", "src"))
    args = ap.parse_args()

    try:
        names = exports_via_pefile(args.winmm)
    except Exception:
        names = exports_via_dumpbin(args.winmm)

    fwd = [n for n in names if n not in OVERRIDES]
    fwd = sorted(set(fwd))
    os.makedirs(args.out, exist_ok=True)

    c = os.path.join(args.out, "forwarders_generated.c")
    with open(c, "w") as f:
        f.write('// AUTO-GENERATED by gen_forwarders.py — do not edit.\n')
        f.write('#include <windows.h>\n#include "proxy.h"\n\n')
        for n in fwd:
            f.write(f'void* p_{n} = 0;\n')
        f.write('\n')
        for n in fwd:
            # x86 naked thunk: jump straight to the real function, args untouched.
            f.write(f'__declspec(naked) void thunk_{n}(void)'
                    f'{{ __asm{{ jmp dword ptr [p_{n}] }} }}\n')
        f.write('\nvoid resolve_forwarders(HMODULE h){\n')
        for n in fwd:
            f.write(f'    p_{n} = (void*)GetProcAddress(h, "{n}");\n')
        f.write('}\n')

    d = os.path.join(args.out, "winmm.def")
    with open(d, "w") as f:
        f.write("LIBRARY winmm\nEXPORTS\n")
        for n in fwd:
            f.write(f"    {n}=thunk_{n}\n")
        for n in sorted(OVERRIDES):
            f.write(f"    {n}\n")   # our own __stdcall impl, undecorated

    print(f"forwarded {len(fwd)} exports, {len(OVERRIDES)} overridden")
    print("wrote", c)
    print("wrote", d)

if __name__ == "__main__":
    main()
