// proxy.h — shared declarations for the winmm -> SDL2 joystick shim.
#pragma once
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <mmsystem.h>

#ifdef __cplusplus
extern "C" {
#endif

// Handle to the *real* system winmm.dll (loaded from %WINDIR%\System32).
extern HMODULE g_realWinmm;

// Generated by scripts/gen_forwarders.py:
//   - one void* p_<Name> per forwarded export
//   - resolve_forwarders(HMODULE) fills them via GetProcAddress
//   - one naked thunk per forwarded export (jmp [p_<Name>])
// Excluded from generation: the joy* functions we implement ourselves.
void resolve_forwarders(HMODULE real);

#ifdef __cplusplus
}
#endif
